[package]
name = "cameleon-gentl"
version = "0.1.0"
authors = ["Cameleon Project Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cameleon-impl = { path = "../cameleon-impl" }
