[package]
name = "cameleon-device"
version = "0.1.0"
authors = ["Cameleon Project Developers"]
edition = "2018"

[dependencies]
thiserror = "1.0.20"
log = "0.4.11"
semver = "0.11.0"
byteorder = "1.3.4"
async-std = { version = "1.8.0", features = ["unstable"] }
const_format = "0.2"
futures = { version = "0.3.5" }
lazy_static = { version = "1.4.0" }
rand = { version = "0.8.0" }
cameleon-impl = { path = "../impl" }

# Dependencies for libusb.
rusb = { version = "0.8.0", optional = true }

[dev-dependencies]
trybuild = { version = "1.0.34" }

[features]
libusb = ["rusb"]

[[example]]
name = "u3v_device_enumeration"
path = "examples/u3v/device_enumeration.rs"

[[example]]
name = "u3v_device_control"
path = "examples/u3v/device_control.rs"
