[package]
name = "cameleon-device"
version = "0.1.0"
authors = ["Cameleon Project Developers"]
edition = "2018"

[dependencies]
thiserror = "1.0.20"
log = "0.4.11"
semver = "0.9.0"
byteorder = "1.3.4"

# Dependencies for usb3 vision device driver
rusb = { version = "0.6.2", optional = true }

[features]
default = ["usb3"]

usb3 = ["rusb"]

[[example]]
name = "usb3_device_enumeration"
path = "examples/usb3/device_enumeration.rs"
required-features = ["usb3"]

[[example]]
name = "usb3_device_control"
path = "examples/usb3/device_control.rs"
required-features = ["usb3"]
