[package]
name = "cameleon-macro-impl"
version = "0.1.0"
authors = ["Cameleon Project Developers"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0.40", features = ["derive", "derive"]}
proc-macro2 = "1.0.21"
quote = "1.0.7"
