[package]
name = "cameleon"
version = "0.1.0"
authors = ["Cameleon Project Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
semver = "0.11.0"

cameleon-device = { path = "../device" }

[dev-dependencies]
trybuild = "1.0.42"

[features]
libusb = ["cameleon-device/libusb"]

[[example]]
name = "u3v_device_register_map"
path = "examples/device/u3v/register_map.rs"
