[package]
name = "cameleon"
version = "0.1.0"
authors = ["Cameleon Project Developers"]
edition = "2018"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
semver = "1.0.0"
zip = "0.5.12"
sha-1 = "0.9.5"
async-std = { version = "1.9.0", features = ["unstable"] }
futures = "0.3.14"
tracing = "0.1.26"
auto_impl = "0.4.1"
cameleon-device = { path = "../device" }
cameleon-genapi = { path = "../genapi" }

rusb = { git = 'https://github.com/Y-Nak/rusb', optional = true }
libc = { version = "0.2", optional = true }

[dev-dependencies]
trybuild = "1.0.42"

[features]
libusb = ["cameleon-device/libusb", "rusb", "libc"]

[[example]]
name = "u3v_register_map"
path = "examples/u3v/register_map.rs"
required-features = ["libusb"]

[[example]]
name = "stream"
path = "examples/stream.rs"
required-features = ["libusb"]
