name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  doc:
    name: Doc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - run: cargo doc --no-deps

  lint:
    name: Rustfmt and clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Clippy with default features
        run: cargo clippy --all-targets -- -D clippy::all -D clippy::pedantic

      - name: Clippy for cameleon-device with libusb
        run:  cargo clippy --all-targets --features libusb -- -D clippy::all -D clippy::pedantic # Check with libusb feature.
        working-directory: device

  test-default-feature:
    name: Test with default features
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Test cameleon
        run: cargo test --all-targets
      # NOTE. --all-targets option doesn't invoke doctest, see https://github.com/rust-lang/cargo/issues/6669.
      - name: Doctest cameleon
        run: cargo test --doc

  test-libusb-feature:
    name: Test with libusb feature
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
        rust:
          - stable
          # - beta
          # - nightly

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install libusb
        run: |
          if [[ ${{ matrix.os }} == "ubuntu-latest" ]]; then
            sudo apt install pkg-config libusb-1.0-0-dev
          elif [[ ${{ matrix.os }} == "macos-latest" ]]; then
            brew install pkg-config libusb
          elif [[ ${{ matrix.os }} == "windows-latest" ]]; then
            git clone https://github.com/microsoft/vcpkg.git --depth 1
            vcpkg/bootstrap-vcpkg.bat
            vcpkg/vcpkg integrate install
            vcpkg/vcpkg install libusb
          fi

      # Test cameleon-device with libusb feature.
      - name: Test cameleon-device with libusb
        run: cargo test --all-targets --features libusb
        working-directory: device
      # Doctest cameleon-device with libusb feature. --all-targets option doesn't invoke doctest, see https://github.com/rust-lang/cargo/issues/6669.
      - name: Doctest cameleon-device
        run: cargo test --doc --features libusb
        working-directory: device

      # Test cameleon-device with libusb feature.
      - name: Test cameleon-gentl with libusb
        run: cargo test --all-targets --features libusb
        working-directory: device

      # Test cameleon with libusb feature.
      - name: Test cameleon with libusb
        run: cargo test --all-targets --features libusb
        working-directory: cameleon
      # Doctest cameleon with libusb feature. --all-targets option doesn't invoke doctest, see https://github.com/rust-lang/cargo/issues/6669.
      - name: Doctest cameleon
        run: cargo test --doc --features libusb
        working-directory: cameleon
